import { StyleSheet } from "react-native";

export const registrationStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0A1628' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  headerIcon: {
    width: 60,
    height: 60,
    borderRadius: 16,
    backgroundColor: '#1E2A3F',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  headerIconText: { fontSize: 28 },
  headerTitle: { fontSize: 24, fontWeight: '700', color: '#FFFFFF' },
  content: { flex: 1, paddingHorizontal: 20 },
  title: {
    fontSize: 28,
    fontWeight: '700',
    color: '#FFFFFF',
    marginTop: 20,
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: '#9CA3AF',
    marginBottom: 24,
    lineHeight: 20,
  },
  footer: {
    flexDirection: 'row',
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: '#1E2A3F',
    backgroundColor: '#0A1628',
  },
  cancelButton: {
    flex: 1,
    paddingVertical: 16,
    borderRadius: 12,
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelText: { fontSize: 16, fontWeight: '600', color: '#9CA3AF' },
  continueButton: {
    flex: 2,
    backgroundColor: '#EF4444',
    paddingVertical: 16,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  continueText: { fontSize: 16, fontWeight: '700', color: '#FFFFFF' },
  card: {
    backgroundColor: '#0F1A2E',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#1E2A3F',
    padding: 20,
    marginBottom: 20,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 20,
  },
  addressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  addButton: { fontSize: 14, fontWeight: '600', color: '#3B82F6' },
  uploadRow: { flexDirection: 'row', gap: 12, marginBottom: 24 },
  fileBox: {
    flex: 1,
    backgroundColor: '#0F1A2E',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#1E2A3F',
    padding: 16,
    justifyContent: 'center',
  },
  fileName: { fontSize: 14, color: '#9CA3AF' },
  addButtonWhite: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderRadius: 12,
    justifyContent: 'center',
  },
  addButtonWhiteText: { fontSize: 14, fontWeight: '700', color: '#0A1628' },
  docCard: {
    backgroundColor: '#0F1A2E',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#1E2A3F',
    padding: 20,
    marginBottom: 20,
  },
  docCardError: { backgroundColor: '#1F1315', borderColor: '#7F1D1D' },
  docHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 20 },
  docIconBox: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: '#1E2A3F',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  docIcon: { fontSize: 24 },
  docName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  docStatus: { fontSize: 14 },
  progressBar: { flexDirection: 'row', alignItems: 'center', marginBottom: 20 },
  progressStep: { alignItems: 'center', flex: 1 },
  progressDot: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#1E2A3F',
    borderWidth: 2,
    borderColor: '#2A3F5F',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  progressDotActive: { backgroundColor: '#4CAF50', borderColor: '#4CAF50' },
  progressDotCurrent: { backgroundColor: '#3B82F6', borderColor: '#3B82F6' },
  progressDotError: { backgroundColor: '#EF4444', borderColor: '#EF4444' },
  progressCheck: { fontSize: 16, color: '#FFFFFF', fontWeight: 'bold' },
  progressNum: { fontSize: 14, fontWeight: '600', color: '#6B7280' },
  progressLine: {
    flex: 1,
    height: 2,
    backgroundColor: '#1E2A3F',
    marginHorizontal: -10,
  },
  progressLabel: { fontSize: 11, color: '#6B7280' },
  successBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0F2922',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#166534',
  },
  successIcon: { fontSize: 16, marginRight: 8 },
  successText: { fontSize: 14, color: '#4ADE80', fontWeight: '500' },
  errorBox: {
    flexDirection: 'row',
    backgroundColor: '#1F1315',
    borderRadius: 8,
    padding: 16,
    borderWidth: 1,
    borderColor: '#7F1D1D',
    marginBottom: 12,
  },
  errorIcon: { fontSize: 16, marginRight: 12 },
  errorTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FCA5A5',
    marginBottom: 4,
  },
  errorDesc: { fontSize: 13, color: '#F87171', lineHeight: 18 },
  reuploadButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    padding: 16,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: '#7F1D1D',
  },
  reuploadIcon: { fontSize: 16, marginRight: 8 },
  reuploadText: { fontSize: 14, fontWeight: '600', color: '#FCA5A5', marginLeft:10 },
  uploadButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    padding: 40,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: '#2A3F5F',
  },
  uploadIcon: { fontSize: 20, marginRight: 8 },
  uploadText: { fontSize: 14, fontWeight: '500', color: '#9CA3AF', marginLeft:10 },
  successContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  successIconLarge: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#0F2922',
    borderWidth: 4,
    borderColor: '#166534',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 32,
  },
  successCheckLarge: { fontSize: 60, color: '#4ADE80', fontWeight: 'bold' },
  successTitle: {
    fontSize: 32,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 16,
  },
  successMessage: {
    fontSize: 16,
    color: '#9CA3AF',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 24,
  },
  appId: { fontWeight: '700', color: '#FFFFFF' },
  infoBoxBlue: {
    flexDirection: 'row',
    backgroundColor: '#0F1A2E',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#1E3A8A',
    padding: 16,
    marginTop: 16,
  },
  infoIconBlue: { fontSize: 16, marginRight: 12 },
  infoTextBlue: { flex: 1, fontSize: 13, color: '#93C5FD', lineHeight: 18 },
  stepContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#1E2A3F',
  },
  stepItem: { alignItems: 'center', flex: 1 },
  stepCircle: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#1E2A3F',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#2A3F5F',
    marginBottom: 6,
  },
  stepActive: { backgroundColor: '#FFFFFF', borderColor: '#FFFFFF' },
  stepCompleted: { backgroundColor: '#4CAF50', borderColor: '#4CAF50' },
  stepNumber: { fontSize: 18, fontWeight: '600', color: '#6B7280' },
  stepNumberActive: { color: '#0A1628' },
  checkmark: { fontSize: 24, color: '#FFFFFF', fontWeight: 'bold' },
  stepLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: '#6B7280',
    textAlign: 'center',
  },
  stepLabelActive: { color: '#FFFFFF' },
  stepSublabel: { fontSize: 9, color: '#4B5563', textAlign: 'center' },
  stepSublabelActive: { color: '#9CA3AF' },
  inputWrapper: { marginBottom: 20 },
  inputLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: '#D1D5DB',
    marginBottom: 8,
  },
  inputContainer: {
    backgroundColor: '#0F1A2E',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#1E2A3F',
    flexDirection: 'row',
    alignItems: 'center',
    // paddingHorizontal: 16,
  },
  inputError: { borderColor: '#EF4444' },
  inputIcon: { fontSize: 20, marginRight: 12 },
  input: { flex: 1, fontSize: 16, color: '#FFFFFF', paddingVertical: 16, paddingHorizontal:5 },
  multilineInput: { minHeight: 100, textAlignVertical: 'top' },
  pickerText: { flex: 1, fontSize: 16, color: '#FFFFFF', paddingVertical: 8 },
  chevron: { fontSize: 10, color: '#9CA3AF' },
  errorText: { fontSize: 12, color: '#EF4444', marginTop: 4, marginLeft: 4 },
});
